version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: config/DockerFile
      target: dev
    container_name: advent_app
    ports:
      - "80:80"
    volumes:
      - ./sources_app:/var/www/html
      - ./data:/var/data
  bdd:
    container_name: advent_bdd
    image: postgres:13.8-alpine3.16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adm"