version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: config/DockerFile
      target: dev
    container_name: advent_app
    ports:
      - "80:80"
    volumes:
      - ./sources_app:/var/www/html
      - ./data:/var/data